version 0.4

diff --git a/dist/bes-build b/dist/bes-build
--- a/dist/bes-build
+++ b/dist/bes-build
@@ -110,9 +110,9 @@ bes.echo.state(){
 bes.echo.rs(){
     local rs=${1:-0}
     if [ "$rs" -eq 0 ]; then
-        echo -e "\n  ${Cdone}  done  ${Coff}"
+        echo -e "  ${Cdone}  done  ${Coff}"
     else 
-        echo -e "\n  ${Cfail}  failed  ${Coff}"
+        echo -e "  ${Cfail}  failed  ${Coff}"
     fi
 }
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@@ -157,25 +157,26 @@ bes.color.map(){
 
 bes.install(){
     local path=${1:-/usr/local/bin}
-
+    local done=1
     bes.echo.title "Installing bes-build ${Coff}in" "$path"
 
     if [ -f "./bes-build" ]; then
         rm ./bes-build
     fi
-    wget -q https://git.pluie.org/meta-tech/bes-build/raw/master/dist/bes-build
+    wget -q https://git.pluie.org/meta-tech/bes-build/raw/latest/dist/bes-build
     if [ $? -eq 0 ]; then
         chmod +x ./bes-build
         if [ -d $path ]; then
-            bes.echo.action "install bes-build in ${Copt}$path/bes-build"
             sudo mv ./bes-build $path/bes-build
-            bes.echo.state $?
+            local done=$?
+            bes.echo.state $done
         else
             bes.echo.error "install directory do not exists : ${Cspe}$path"
         fi
     else 
         bes.echo.error "can not download latest version of bes-build"        
     fi
+    bes.echo.rs $done
 }
 
 bes.usage(){
@@ -194,7 +195,7 @@ bes.usage(){
     echo -e "${Coff}"
 }
 
-BES_BUILD_VERSION=0.3
+BES_BUILD_VERSION=0.4
           APP_DIR=$(pwd)
          APP_NAME=$(basename $(pwd)) 
           APP_BIN=$APP_DIR/dist/$APP_NAME
